local base = {
    base0A = "#f5d595",
    base04 = "#4f565d",
    base07 = "#b5bcc9",
    base05 = "#ced4df",
    base0E = "#c2a2e3",
    base0D = "#a3b8ef",
    base0C = "#abb9e0",
    base0B = "#a5d4af",
    base02 = "#31383f",
    base0F = "#e88e9b",
    base03 = "#40474e",
    base08 = "#ef8891",
    base01 = "#2c333a",
    base00 = "#131a21",
    base09 = "#EDA685",
    base06 = "#d3d9e4",
    white = "#b5bcc9",
    darker_black = "#10171e",
    black = "#131a21", --  nvim bg
    black2 = "#1a2128",
    one_bg = "#1e252c",
    one_bg2 = "#2a3138",
    one_bg3 = "#363d44",
    grey = "#363d44",
    grey_fg = "#4e555c",
    grey_fg2 = "#51585f",
    light_grey = "#545b62",
    red = "#ef8891",
    baby_pink = "#fca2aa",
    pink = "#fca2af",
    line = "#20272e", -- for lines like vertsplit
    green = "#9ce5c0",
    vibrant_green = "#a5d4af",
    blue = "#99aee5",
    nord_blue = "#9aa8cf",
    yellow = "#fbdf90",
    sun = "#fbdf9a",
    purple = "#d7c1ed",
    dark_purple = "#ccaced",
    teal = "#92dbb6",
    orange = "#EDA685",
    cyan = "#b5c3ea",
    statusline_bg = "#181f26",
    lightbg = "#222930",
    lightbg2 = "#1d242b",
    pmenu_bg = "#ef8891",
    folder_bg = "#99aee5",
}

local cp = {
    -- Legacy colors for compatibility
    red = base.red,
    yellow = base.yellow,
    orange = base.orange,
    magenta = base.dark_purple,
    blue = base.blue,
    green = base.green,
    cyan = base.teal,

    -- The new shiny boy
    fg = base.white,
    diff = {
        add = base.green,
        remove = base.red,
        text = base.blue,
        change = base.yellow,
    },
    accent = base.base0C,
    search_result = { fg = base.base01, bg = base.base0A, telescope = base.base0A },
    match = base.base06,
    dimmed = {
        inactive = base.base03,
        subtle = base.grey_fg,
    },
    bg = {
        base = base.base00,
        alt = base.darker_black,
        selected = base.base02,
    },
    border = base.blue,
    syntax = {
        statement = base.base08,
        ["function"] = base.base0D,
        variable = base.base05,
        include = base.base0D,
        keyword = base.base0E,
        struct = base.base0E,
        string = base.base0B,
        identifier = base.base08,
        field = base.base08,
        parameter = base.base08,
        property = base.base08,
        punctuation = base.base0F,
        constructor = base.base0C,
        operator = base.base05,
        preproc = base.base0A,
        constant = base.base09,
        todo = { fg = base.base0A, bg = base.base01 },
        number = base.base09,
        comment = base.base03,
        type = base.base0A,
        conditional = base.base0E,
    },
    built_in = {
        ["function"] = base.base0C,
        type = base.base0A,
        variable = base.base0C,
        keyword = base.base0E,
        constant = base.base09,
    },
    directory = base.folder_bg,
    diagnostic = {
        error = base.red,
        warn = base.yellow,
        info = base.green,
        hint = base.purple,
    },
    inc_search = { fg = base.base01, bg = base.base09 },
    uri = base.base08,
    pum = {
        fg = base.base06,
        bg = base.one_bg,
        sbar = base.one_bg2,
        thumb = base.nord_blue,
        sel = {
            bg = base.pmenu_bg,
            fg = base.base05,
        },
    },
    heading = {
        h1 = base.blue,
        h2 = base.blue,
    },
}

return cp
