local base = {
    base0A = "#e0af68",
    base04 = "#565c64",
    base07 = "#c0caf5",
    base05 = "#a9b1d6",
    base0E = "#9d7cd8",
    base0D = "#7aa2f7",
    base0C = "#2ac3de",
    base0B = "#9ece6a",
    base02 = "#3b4261",
    base0F = "#9abdf5",
    base03 = "#545c7e",
    base08 = "#f7768e",
    base01 = "#3b4261",
    base00 = "#1A1B26",
    base09 = "#ff9e64",
    base06 = "#bbc5f0",
    white = "#abb2bf",
    darker_black = "#1b1f27",
    black = "#1e222a", --  nvim bg
    black2 = "#252931",
    one_bg = "#282c34", -- real bg of tokyonight
    one_bg2 = "#353b45",
    one_bg3 = "#30343c",
    grey = "#42464e",
    grey_fg = "#565c64",
    grey_fg2 = "#6f737b",
    light_grey = "#6f737b",
    red = "#d47d85",
    baby_pink = "#DE8C92",
    pink = "#ff75a0",
    line = "#2a2e36", -- for lines like vertsplit
    green = "#A3BE8C",
    vibrant_green = "#7eca9c",
    nord_blue = "#81A1C1",
    blue = "#61afef",
    yellow = "#e7c787",
    sun = "#EBCB8B",
    purple = "#b4bbc8",
    dark_purple = "#c882e7",
    teal = "#519ABA",
    orange = "#fca2aa",
    cyan = "#a3b8ef",
    statusline_bg = "#22262e",
    lightbg = "#2d3139",
    lightbg2 = "#262a32",
    pmenu_bg = "#A3BE8C",
    folder_bg = "#61afef",
}

local cp = {
    -- Legacy colors for compatibility
    red = base.red,
    yellow = base.yellow,
    orange = base.orange,
    magenta = base.dark_purple,
    blue = base.blue,
    green = base.green,
    cyan = base.teal,

    -- The new shiny boy
    directory = base.folder_bg,
    fg = base.white,
    diff = {
        add = base.green,
        remove = base.red,
        text = base.blue,
        change = base.yellow,
    },
    accent = base.base0C,
    search_result = { fg = base.base01, bg = base.base0A, telescope = base.base0A },
    match = base.base06,
    dimmed = {
        inactive = base.base03,
        subtle = base.grey_fg,
    },
    bg = {
        base = base.base00,
        alt = base.darker_black,
        selected = base.base02,
    },
    border = base.blue,
    syntax = {
        statement = base.base08,
        ["function"] = base.base0D,
        variable = base.base05,
        include = base.base0D,
        keyword = base.base0E,
        struct = base.base0E,
        string = base.base0B,
        identifier = base.base08,
        field = base.base08,
        parameter = base.base08,
        property = base.base08,
        punctuation = base.base0F,
        constructor = base.base0C,
        operator = base.base05,
        preproc = base.base0A,
        constant = base.base09,
        todo = { fg = base.base0A, bg = base.base01 },
        number = base.base09,
        comment = base.base03,
        type = base.base0A,
        conditional = base.base0E,
    },
    built_in = {
        ["function"] = base.base0C,
        type = base.base0A,
        variable = base.base0C,
        keyword = base.base0E,
        constant = base.base09,
    },
    diagnostic = {
        error = base.red,
        warn = base.yellow,
        info = base.green,
        hint = base.purple,
    },
    inc_search = { fg = base.base01, bg = base.base09 },
    uri = base.base08,
    pum = {
        fg = base.base06,
        bg = base.one_bg,
        sbar = base.one_bg2,
        thumb = base.nord_blue,
        sel = {
            bg = base.pmenu_bg,
            fg = base.base05,
        },
    },
    heading = {
        h1 = base.blue,
        h2 = base.blue,
    },
}

return cp
