local base = {
  base00 = "#23233d",
  base01 = "#ed3f7f",
  base02 = "#84c49b",
  base03 = "#f6e08b",
  base04 = "#a29dff",
  base05 = "#ed86ea",
  base06 = "#93c5e6",
  base07 = "#f47d49",
  base08 = "#2f2e51",
  base09 = "#fb5c8e",
  base0A = "#9fd3b3",
  base0B = "#fff0b8",
  base0C = "#b2aeff",
  base0D = "#f09eed",
  base0E = "#aed9f6",
  base0F = "#f79f79",
  white = "#dedbeb",
  darker_black = "#1a1a2e",
  black = "#161627", --  nvim bg
  grey = "#565393",
  red = "#ed3f7f",
  pink = "#e68ac1",
  line = "#2c223c", -- for lines like vertsplit
  green = "#84c49b",
  vibrant_green = "#9fd3b3",
  nord_blue = "#b3dfef",
  blue = "#bdceed",
  yellow = "#f7d98d",
  sun = "#ffb65e",
  purple = "#b4a4de",
  dark_purple = "#9985d1",
  teal = "#a2baa8",
  orange = "#e78a4e",
  cyan = "#aabae7",
  statusline_bg = "#1a1a2e",
  lightbg = "#414e58",
  lightbg2 = "#6c8391",
  pmenu_bg = "#313a43",
  folder_bg = "#df8b92",
}

local cp = {
  -- Legacy colors for compatibility
  red = base.red,
  yellow = base.yellow,
  orange = base.orange,
  magenta = base.dark_purple,
  blue = base.blue,
  green = base.green,
  cyan = base.teal,

  -- The new shiny boy
  directory = base.folder_bg,
  fg = base.white,
  diff = {
    add = base.green,
    remove = base.red,
    text = base.blue,
    change = base.sun,
  },
  -- cursorlinenr = base.line,
  accent = base.base0D,
  search_result = { fg = base.darker_black, bg = base.red, telescope = base.darker_black },
  match = base.lightbg2,
  dimmed = {
    inactive = base.base00,
    subtle = base.grey,
  },
  bg = {
    base = base.darker_black,
    alt = base.line,
    selected = base.line,
  },
  border = base.purple,
  syntax = {
    tag = base.base0E,
    statement = base.base0D,
    ["function"] = base.base04,
    variable = base.white,
    include = base.base09,
    keyword = base.base01,
    struct = base.base03,
    string = base.base0A,
    identifier = base.base02,
    field = base.base07,
    parameter = base.base0F,
    property = base.base0C,
    punctuation = base.pink,
    constructor = base.base05,
    operator = base.pink,
    preproc = base.sun,
    constant = base.purple,
    todo = { fg = base.white, bg = base.red },
    number = base.purple,
    comment = base.grey,
    type = base.base06,
    conditional = base.folder_bg,
  },
  built_in = {
    ["function"] = base.base04,
    type = base.yellow,
    variable = base.base06,
    keyword = base.base09,
    constant = base.purple,
  },
  diagnostic = {
    error = base.red,
    warn = base.base0F,
    info = base.green,
    hint = base.base06,
  },
  inc_search = { fg = base.darker_black, bg = base.purple },
  uri = base.base02,
  pum = {
    fg = base.white,
    bg = base.grey,
    sbar = base.pmenu_bg,
    thumb = base.nord_blue,
    sel = {
      bg = base.base04,
      fg = base.black,
    },
  },
  heading = {
    h1 = base.dark_purple,
    h2 = base.purple,
  },
}

return cp
