return {
  ["search_result"] = {
    ["bg"] = "#e5c07b",
    ["fg"] = "#282c34",
    ["telescope"] = "#e5c07b",
  },
  ["cursorlinenr"] = "#abb2bf",
  ["gitsigns"] = {
    ["change"] = "#ff9640",
    ["remove"] = "#ec5f67",
    ["add"] = "#98c379",
  },
  ["diff"] = {
    ["text"] = "#e5c07b",
    ["remove"] = "#e06c75",
    ["add"] = "#98c379",
    ["change"] = "#abb2bf",
  },
  ["match"] = "#569cd6",
  ["dimmed"] = {
    ["subtle"] = "#5c6370",
    ["inactive"] = "#4b5263",
  },
  ["inc_search"] = {
    ["bg"] = "#5c6370",
    ["fg"] = "#40d9ff",
  },
  ["bg"] = {
    ["base"] = "#15171c",
    ["alt"] = "#1f1f25",
    ["selected"] = "#252931",
  },
  ["pum"] = {
    ["sbar"] = "#282c34",
    ["thumb"] = "#abb2bf",
    ["bg"] = "#1f1f25",
    ["sel"] = {
      ["bg"] = "#2c323c",
      ["fg"] = "#abb2bf",
    },
    ["fg"] = "#abb2bf",
  },
  ["border"] = "#abb2bf",
  ["diagnostic"] = {
    ["warn"] = "#ff9640",
    ["hint"] = "#ebae34",
    ["error"] = "#ec5f67",
    ["info"] = "#c9c9c9",
  },
  ["syntax"] = {
    ["constant"] = "#e5c07b",
    ["struct"] = "#e5c07b",
    ["punctuation"] = "#abb2bf",
    ["preproc"] = "#e5c07b",
    ["todo"] = {
      ["fg"] = "#c678dd",
      ["bg"] = "#abb2bf",
    },
    ["tag"] = "#e06c75",
    ["statement"] = "#c678dd",
    ["string"] = "#98c379",
    ["comment"] = "#777d86",
    ["function"] = "#61afef",
    ["field"] = "#e06c75",
    ["number"] = "#d19a66",
    ["keyword"] = "#c678dd",
    ["type"] = "#61afef",
    ["operator"] = "#56b6c2",
    ["include"] = "#c678dd",
    ["variable"] = "#e06c75",
    ["constructor"] = "#e5c07b",
    ["property"] = "#e5c07b",
    ["parameter"] = "#e06c75",
    ["conditional"] = "#c678dd",
  },
  ["fg"] = "#abb2bf",
  ["built_in"] = {
    ["constant"] = "#d19a66",
    ["variable"] = "#e5c07b",
    ["function"] = "#61afef",
    ["type"] = "#61afef",
    ["keyword"] = "#c678dd",
  },
  ["uri"] = "#abb2bf",
  ["accent"] = "#61afef",
  ["heading"] = {
    ["h1"] = "#56b6c2",
    ["h2"] = "#abb2bf",
  },
}
