return {
  ["search_result"] = {
    ["bg"] = "#d4bfff",
    ["fg"] = "#212733",
    ["telescope"] = "#d9d7ce",
  },
  ["cursorlinenr"] = "#ffcc66",
  ["diff"] = {
    ["text"] = "#272d38",
    ["remove"] = "#8b8b",
    ["add"] = "#272d38",
    ["change"] = "#272d38",
  },
  ["match"] = "#d9d7ce",
  ["built_in"] = {
    ["constant"] = "#ffc44c",
    ["variable"] = "#ffc44c",
    ["function"] = "#ffc44c",
    ["keyword"] = "#ffae57",
    ["type"] = "#5ccfe6",
  },
  ["heading"] = {
    ["h2"] = "#d9d7ce",
    ["h1"] = "#d9d7ce",
  },
  ["bg"] = {
    ["base"] = "#212733",
    ["alt"] = "#343f4c",
    ["selected"] = "#242b38",
  },
  ["pum"] = {
    ["sbar"] = "#808080",
    ["thumb"] = "#ffffff",
    ["bg"] = "#343f4c",
    ["sel"] = {
      ["bg"] = "#343f4c",
      ["fg"] = "#d9d7ce",
    },
    ["fg"] = "#d9d7ce",
  },
  ["orange"] = "#FFCC66",
  ["diagnostic"] = {
    ["warn"] = "#ffa500",
    ["info"] = "#add8e6",
    ["hint"] = "#d3d3d3",
    ["error"] = "#ff0000",
  },
  ["syntax"] = {
    ["constant"] = "#d4bfff",
    ["struct"] = "#ffc44c",
    ["punctuation"] = "#ffc44c",
    ["preproc"] = "#ffc44c",
    ["todo"] = {
      ["fg"] = "#f07178",
      ["bg"] = "#d9d7ce",
    },
    ["tag"] = "#ffae57",
    ["statement"] = "#ffae57",
    ["string"] = "#bbe67e",
    ["comment"] = "#5c6773",
    ["function"] = "#ffd57f",
    ["field"] = "#5ccfe6",
    ["number"] = "#d4bfff",
    ["keyword"] = "#ffae57",
    ["type"] = "#5ccfe6",
    ["operator"] = "#80d4ff",
    ["include"] = "#ffc44c",
    ["variable"] = "#d9d7ce",
    ["constructor"] = "#ffc44c",
    ["property"] = "#5ccfe6",
    ["parameter"] = "#5ccfe6",
    ["conditional"] = "#ffae57",
  },
  ["yellow"] = "#FFCC66",
  ["cyan"] = "#95E6CB",
  ["green"] = "#BBE67E",
  ["border"] = "#212733",
  ["blue"] = "#5CCFE6",
  ["fg"] = "#d9d7ce",
  ["magenta"] = "#D4BFFF",
  ["inc_search"] = {
    ["bg"] = "#d9d7ce",
    ["fg"] = "#d9d7ce",
  },
  ["uri"] = "#5ccfe6",
  ["accent"] = "#ffc44c",
  ["dimmed"] = {
    ["subtle"] = "#607080",
    ["inactive"] = "#3d4751",
  },
}
