local cp = {
  rosewater = "#F5E0DC",
  flamingo = "#F2CDCD",
  pink = "#F5C2E7",
  mauve = "#CBA6F7",
  red = "#F38BA8",
  maroon = "#EBA0AC",
  peach = "#FAB387",
  yellow = "#F9E2AF",
  green = "#A6E3A1",
  teal = "#94E2D5",
  sky = "#89DCEB",
  sapphire = "#74C7EC",
  blue = "#89B4FA",
  lavender = "#B4BEFE",

  text = "#CDD6F4",
  subtext1 = "#BAC2DE",
  subtext0 = "#A6ADC8",
  overlay2 = "#9399B2",
  overlay1 = "#7F849C",
  overlay0 = "#6C7086",
  surface2 = "#585B70",
  surface1 = "#45475A",
  surface0 = "#313244",

  base = "#1E1E2E",
  mantle = "#181825",
  crust = "#11111B",
}

return {
  ["accent"] = cp.pink,
  ["gitsigns"] = {
    ["add"] = cp.green,
    ["change"] = cp.yellow,
    ["remove"] = cp.red,
  },
  ["cyan"] = cp.sky,
  ["uri"] = cp.rosewater,
  ["green"] = cp.green,
  ["blue"] = cp.blue,
  ["magenta"] = cp.pink,
  ["match"] = cp.text,
  ["orange"] = cp.peach,
  ["fg"] = cp.text,
  ["yellow"] = cp.yellow,
  ["diagnostic"] = {
    ["error"] = cp.red,
    ["info"] = cp.sky,
    ["hint"] = cp.rosewater,
    ["warn"] = cp.yellow,
  },
  ["pum"] = {
    ["bg"] = cp.surface0,
    ["fg"] = cp.overlay2,
    ["sbar"] = cp.surface1,
    ["sel"] = { ["fg"] = cp.text, ["bg"] = cp.surface1 },
    ["thumb"] = cp.overlay0,
  },
  ["inc_search"] = { ["fg"] = cp.surface1, ["bg"] = cp.pink },
  ["heading"] = { ["h2"] = "#0", ["h1"] = cp.pink },
  ["built_in"] = {
    ["constant"] = cp.peach,
    ["function"] = cp.peach,
    ["keyword"] = cp.mauve,
    ["type"] = cp.yellow,
    ["variable"] = cp.red,
  },
  ["syntax"] = {
    ["comment"] = cp.surface2,
    ["conditional"] = cp.mauve,
    ["constant"] = cp.peach,
    ["constructor"] = cp.sapphire,
    ["field"] = cp.teal,
    ["function"] = cp.blue,
    ["include"] = cp.pink,
    ["keyword"] = cp.mauve,
    ["number"] = cp.peach,
    ["operator"] = cp.sky,
    ["parameter"] = cp.maroon,
    ["preproc"] = cp.pink,
    ["property"] = cp.teal,
    ["punctuation"] = cp.overlay2,
    ["statement"] = cp.mauve,
    ["string"] = cp.green,
    ["struct"] = cp.yellow,
    ["tag"] = cp.mauve,
    ["todo"] = { ["fg"] = cp.base, ["bg"] = cp.yellow },
    ["type"] = cp.yellow,
    ["variable"] = cp.text,
  },
  ["cursorlinenr"] = cp.lavender,
  ["dimmed"] = { ["inactive"] = cp.overlay0, ["subtle"] = cp.surface1 },
  ["border"] = cp.blue,
  ["bg"] = {
    ["alt"] = cp.mantle,
    ["base"] = cp.base,
    ["selected"] = cp.surface0,
  },
  ["diff"] = {
    ["add"] = cp.base,
    ["text"] = cp.base,
    ["change"] = cp.base,
    ["remove"] = cp.base,
  },
  ["search_result"] = {
    ["fg"] = cp.pink,
    ["bg"] = cp.surface1,
    ["telescope"] = cp.blue,
  },
}
