return {
  ["search_result"] = {
    ["telescope"] = "#89b4fa",
    ["fg"] = "#cdd6f4",
    ["bg"] = "#3e5767",
  },
  ["cursorlinenr"] = "#b4befe",
  ["diff"] = {
    ["change"] = "#25293c",
    ["remove"] = "#443244",
    ["add"] = "#364143",
    ["text"] = "#313953",
  },
  ["match"] = "#cdd6f4",
  ["built_in"] = {
    ["function"] = "#f5c2e7",
    ["variable"] = "#f2cdcd",
    ["constant"] = "#f5c2e7",
    ["type"] = "#89b4fa",
    ["keyword"] = "#f5c2e7",
  },
  ["inc_search"] = {
    ["bg"] = "#7ec9d8",
    ["fg"] = "#181825",
  },
  ["bg"] = {
    ["selected"] = "#2a2b3c",
    ["alt"] = "#cdd6f4",
    ["base"] = "#1e1e2e",
  },
  ["uri"] = "#cdd6f4",
  ["border"] = "#89b4fa",
  ["diagnostic"] = {
    ["warn"] = "#f9e2af",
    ["error"] = "#f38ba8",
    ["hint"] = "#94e2d5",
    ["info"] = "#89dceb",
  },
  ["syntax"] = {
    ["constant"] = "#fab387",
    ["struct"] = "#f9e2af",
    ["punctuation"] = "#f5c2e7",
    ["preproc"] = "#f5c2e7",
    ["todo"] = {
      ["fg"] = "#1e1e2e",
      ["bg"] = "#f9e2af",
    },
    ["tag"] = "#f5c2e7",
    ["statement"] = "#cba6f7",
    ["string"] = "#a6e3a1",
    ["comment"] = "#585b70",
    ["function"] = "#89b4fa",
    ["field"] = "#f2cdcd",
    ["number"] = "#fab387",
    ["keyword"] = "#f5c2e7",
    ["type"] = "#89b4fa",
    ["operator"] = "#89dceb",
    ["include"] = "#f5c2e7",
    ["variable"] = "#f2cdcd",
    ["constructor"] = "#f5c2e7",
    ["property"] = "#f2cdcd",
    ["parameter"] = "#f2cdcd",
    ["conditional"] = "#f38ba8",
  },
  ["yellow"] = "#f6c177",
  ["cyan"] = "#ebbcba",
  ["heading"] = {
    ["h2"] = "#cdd6f4",
    ["h1"] = "#f5c2e7",
  },
  ["green"] = "#31748f",
  ["gitsigns"] = {
    ["change"] = "#f9e2af",
    ["remove"] = "#f38ba8",
    ["add"] = "#a6e3a1",
  },
  ["blue"] = "#9ccfd8",
  ["fg"] = "#cdd6f4",
  ["magenta"] = "#c4a7e7",
  ["orange"] = "#f6c177",
  ["pum"] = {
    ["sbar"] = "#45475a",
    ["thumb"] = "#6c7086",
    ["bg"] = "#313244",
    ["sel"] = {
      ["bg"] = "#45475a",
      ["fg"] = "#cdd6f4",
    },
    ["fg"] = "#9399b2",
  },
  ["accent"] = "#f5c2e7",
  ["dimmed"] = {
    ["subtle"] = "#45475a",
    ["inactive"] = "#6c7086",
  },
}
