return {
  ["search_result"] = {
    ["telescope"] = "#96cdfb",
    ["fg"] = "#f5c2e7",
    ["bg"] = "#575268",
  },
  ["cursorlinenr"] = "#abe9b3",
  ["diff"] = {
    ["text"] = "#1e1e2e",
    ["remove"] = "#1e1e2e",
    ["add"] = "#1e1e2e",
    ["change"] = "#1e1e2e",
  },
  ["match"] = "#d9e0ee",
  ["built_in"] = {
    ["constant"] = "#c9cbff",
    ["variable"] = "#b5e8e0",
    ["function"] = "#f8bd96",
    ["keyword"] = "#e8a2af",
    ["type"] = "#fae3b0",
  },
  ["heading"] = {
    ["h2"] = "#d9e0ee",
    ["h1"] = "#f5c2e7",
  },
  ["bg"] = {
    ["base"] = "#1e1e2e",
    ["alt"] = "#1a1826",
    ["selected"] = "#302d41",
  },
  ["pum"] = {
    ["sbar"] = "#575268",
    ["thumb"] = "#6e6c7e",
    ["bg"] = "#302d41",
    ["sel"] = {
      ["fg"] = "#d9e0ee",
      ["bg"] = "#575268",
    },
    ["fg"] = "#c3bac6",
  },
  ["orange"] = "#FAE3B0",
  ["diagnostic"] = {
    ["warn"] = "#fae3b0",
    ["hint"] = "#f5e0dc",
    ["error"] = "#f28fad",
    ["info"] = "#89dceb",
  },
  ["syntax"] = {
    ["constant"] = "#f8bd96",
    ["struct"] = "#fae3b0",
    ["punctuation"] = "#988ba2",
    ["preproc"] = "#f5c2e7",
    ["todo"] = {
      ["bg"] = "#fae3b0",
      ["fg"] = "#1e1e2e",
    },
    ["tag"] = "#f8bd96",
    ["statement"] = "#ddb6f2",
    ["string"] = "#abe9b3",
    ["comment"] = "#6e6c7e",
    ["operator"] = "#89dceb",
    ["field"] = "#f5e0dc",
    ["number"] = "#f8bd96",
    ["type"] = "#fae3b0",
    ["keyword"] = "#f28fad",
    ["function"] = "#96cdfb",
    ["include"] = "#f5c2e7",
    ["variable"] = "#d9e0ee",
    ["constructor"] = "#c9cbff",
    ["property"] = "#fae3b0",
    ["parameter"] = "#f5e0dc",
    ["conditional"] = "#ddb6f2",
  },
  ["yellow"] = "#FAE3B0",
  ["cyan"] = "#B5E8E0",
  ["border"] = "#96cdfb",
  ["green"] = "#ABE9B3",
  ["gitsigns"] = {
    ["change"] = "#fae3b0",
    ["remove"] = "#f28fad",
    ["add"] = "#abe9b3",
  },
  ["blue"] = "#96CDFB",
  ["fg"] = "#d9e0ee",
  ["magenta"] = "#DDB6F2",
  ["dimmed"] = {
    ["subtle"] = "#575268",
    ["inactive"] = "#6e6c7e",
  },
  ["uri"] = "#f5e0dc",
  ["accent"] = "#f5c2e7",
  ["inc_search"] = {
    ["fg"] = "#575268",
    ["bg"] = "#f5c2e7",
  },
}
