return {
  ["search_result"] = {
    ["bg"] = "#a8daf0",
    ["telescope"] = "#1e66f5",
    ["fg"] = "#4c4f69",
  },
  ["cursorlinenr"] = "#7287fd",
  ["diff"] = {
    ["text"] = "#c9d8f5",
    ["remove"] = "#eac8d3",
    ["add"] = "#d0e2d1",
    ["change"] = "#e0e7f5",
  },
  ["match"] = "#4c4f69",
  ["built_in"] = {
    ["function"] = "#fe640b",
    ["variable"] = "#d20f39",
    ["keyword"] = "#8839ef",
    ["constant"] = "#fe640b",
    ["type"] = "#df8e1d",
  },
  ["heading"] = {
    ["h1"] = "#ea76cb",
    ["h2"] = "#4c4f69",
  },
  ["bg"] = {
    ["base"] = "#eff1f5",
    ["alt"] = "#4c4f69",
    ["selected"] = "#e9ebf1",
  },
  ["pum"] = {
    ["sbar"] = "#bcc0cc",
    ["thumb"] = "#9ca0b0",
    ["fg"] = "#7c7f93",
    ["sel"] = {
      ["fg"] = "#4c4f69",
      ["bg"] = "#bcc0cc",
    },
    ["bg"] = "#ccd0da",
  },
  ["orange"] = "#f6c177",
  ["diagnostic"] = {
    ["warn"] = "#df8e1d",
    ["error"] = "#d20f39",
    ["info"] = "#4a5e5",
    ["hint"] = "#179299",
  },
  ["syntax"] = {
    ["constant"] = "#fe640b",
    ["struct"] = "#df8e1d",
    ["punctuation"] = "#7c7f93",
    ["preproc"] = "#ea76cb",
    ["todo"] = {
      ["fg"] = "#eff1f5",
      ["bg"] = "#df8e1d",
    },
    ["tag"] = "#8839ef",
    ["statement"] = "#8839ef",
    ["string"] = "#40a02b",
    ["comment"] = "#acb0be",
    ["operator"] = "#4a5e5",
    ["field"] = "#179299",
    ["number"] = "#fe640b",
    ["keyword"] = "#8839ef",
    ["type"] = "#df8e1d",
    ["function"] = "#1e66f5",
    ["include"] = "#ea76cb",
    ["variable"] = "#4c4f69",
    ["constructor"] = "#209fb5",
    ["property"] = "#179299",
    ["parameter"] = "#e64553",
    ["conditional"] = "#8839ef",
  },
  ["yellow"] = "#f6c177",
  ["cyan"] = "#ebbcba",
  ["dimmed"] = {
    ["inactive"] = "#9ca0b0",
    ["subtle"] = "#bcc0cc",
  },
  ["green"] = "#31748f",
  ["gitsigns"] = {
    ["change"] = "#df8e1d",
    ["remove"] = "#d20f39",
    ["add"] = "#40a02b",
  },
  ["blue"] = "#9ccfd8",
  ["fg"] = "#4c4f69",
  ["magenta"] = "#c4a7e7",
  ["border"] = "#1e66f5",
  ["uri"] = "#dc8a78",
  ["accent"] = "#ea76cb",
  ["inc_search"] = {
    ["fg"] = "#e6e9ef",
    ["bg"] = "#1bade7",
  },
}
