return {
  ["search_result"] = {
    ["telescope"] = "#bbc2cf",
    ["bg"] = "#2257a0",
    ["fg"] = "#bbc2cf",
  },
  ["cursorlinenr"] = "#bbc2cf",
  ["diff"] = {
    ["change"] = "#42534f",
    ["remove"] = "#7e7278",
    ["add"] = "#42534f",
    ["text"] = "#384643",
  },
  ["match"] = "#bbc2cf",
  ["built_in"] = {
    ["function"] = "#ffa8ff",
    ["variable"] = "#8b93e6",
    ["keyword"] = "#51afef",
    ["constant"] = "#a9a1e1",
    ["type"] = "#ecbe7b",
  },
  ["heading"] = {
    ["h1"] = "#bbc2cf",
    ["h2"] = "#bbc2cf",
  },
  ["bg"] = {
    ["base"] = "#282c34",
    ["alt"] = "#21252a",
    ["selected"] = "#21252a",
  },
  ["pum"] = {
    ["sbar"] = "#21242b",
    ["thumb"] = "#bbc2cf",
    ["bg"] = "#21252a",
    ["sel"] = {
      ["bg"] = "#51afef",
      ["fg"] = "#1b2229",
    },
    ["fg"] = "#bbc2cf",
  },
  ["border"] = "#3f444a",
  ["diagnostic"] = {
    ["warn"] = "#ffa500",
    ["info"] = "#add8e6",
    ["error"] = "#ff0000",
    ["hint"] = "#d3d3d3",
  },
  ["syntax"] = {
    ["constant"] = "#a9a1e1",
    ["struct"] = "#51afef",
    ["punctuation"] = "#51afef",
    ["preproc"] = "#a9a1e1",
    ["todo"] = {
      ["bg"] = "#bbc2cf",
      ["fg"] = "#ecbe7b",
    },
    ["statement"] = "#51afef",
    ["string"] = "#98be65",
    ["comment"] = "#5b6268",
    ["operator"] = "#51afef",
    ["field"] = "#a9a1e1",
    ["number"] = "#da8548",
    ["keyword"] = "#51afef",
    ["type"] = "#ecbe7b",
    ["function"] = "#c678dd",
    ["include"] = "#a9a1e1",
    ["variable"] = "#bbc2cf",
    ["constructor"] = "#51afef",
    ["property"] = "#c678dd",
    ["parameter"] = "#ffa8ff",
    ["conditional"] = "#51afef",
  },
  ["yellow"] = "#C0A36E",
  ["cyan"] = "#6A9589",
  ["green"] = "#76946A",
  ["uri"] = "#98be65",
  ["blue"] = "#7E9CD8",
  ["fg"] = "#bbc2cf",
  ["magenta"] = "#957FB8",
  ["orange"] = "#C0A36E",
  ["dimmed"] = {
    ["subtle"] = "#73797e",
    ["inactive"] = "#5b6268",
  },
  ["accent"] = "#a9a1e1",
  ["inc_search"] = {
    ["bg"] = "#2257a0",
    ["fg"] = "#bbc2cf",
  },
}
