return {
    ["orange"] = "#b08800",
    ["cyan"] = "#0598bc",
    ["match"] = "#366d6",
    ["fg"] = "#24292f",
    ["heading"] = { ["h1"] = "#0", ["h2"] = "#0" },
    ["diff"] = { ["change"] = "#fff5b1", ["remove"] = "#fae5e7", ["add"] = "#d4f8db", ["text"] = "#0" },
    ["magenta"] = "#5a32a3",
    ["accent"] = "#5cc5",
    ["bg"] = { ["base"] = "#ffffff", ["alt"] = "#ffffff", ["selected"] = "#d5e5f6" },
    ["green"] = "#28a745",
    ["uri"] = "#0",
    ["diagnostic"] = { ["error"] = "#cb2431", ["info"] = "#75beff", ["warn"] = "#bf8803", ["hint"] = "#6c6c6c" },
    ["cursorlinenr"] = "#24292e",
    ["syntax"] = {
        ["field"] = "#24292f",
        ["variable"] = "#5cc5",
        ["keyword"] = "#d73a49",
        ["struct"] = "#d73a49",
        ["parameter"] = "#24292e",
        ["property"] = "#6f42c1",
        ["comment"] = "#6a737d",
        ["punctuation"] = "#24292f",
        ["constructor"] = "#5cc5",
        ["operator"] = "#d73a49",
        ["constant"] = "#5cc5",
        ["todo"] = { ["bg"] = "#dbab09", ["fg"] = "#ffffff" },
        ["conditional"] = "#d73a49",
        ["statement"] = "#d73a49",
        ["type"] = "#d73a49",
        ["tag"] = "#22863a",
        ["function"] = "#6f42c1",
        ["preproc"] = "#d73a49",
        ["number"] = "#5cc5",
        ["include"] = "#d73a49",
        ["string"] = "#32f62",
    },
    ["border"] = "#44289",
    ["yellow"] = "#dbab09",
    ["built_in"] = {
        ["variable"] = "#5cc5",
        ["type"] = "#d73a49",
        ["constant"] = "#5cc5",
        ["function"] = "#5cc5",
        ["keyword"] = "#d73a49",
    },
    ["inc_search"] = { ["bg"] = "#fff2be", ["fg"] = "#0" },
    ["pum"] = {
        ["sel"] = { ["bg"] = "#4085d4", ["fg"] = "#f6f8fa" },
        ["bg"] = "#f6f8fa",
        ["fg"] = "#24292f",
        ["thumb"] = "#f0f1f3",
        ["sbar"] = "#f6f8fa",

    },
    ["search_result"] = { ["telescope"] = "#5cc5", ["fg"] = "#0", ["bg"] = "#fff2be" },
    ["blue"] = "#0366d6",
    ["dimmed"] = { ["inactive"] = "#ffffff", ["subtle"] = "#ffffff" },
}