local base = {
  base00 = "#18191f",
  base01 = "#222329",
  base02 = "#2c2d33",
  base03 = "#3c3d43",
  base04 = "#b5ac9b",
  base05 = "#cbc0ab",
  base06 = "#e0d6bd",
  base07 = "#f1ebd1",
  base08 = "#b8aad9",
  base09 = "#b17f81",
  base0A = "#d4ae80",
  base0B = "#8aa387",
  base0C = "#9ba292",
  base0D = "#c495a2",
  base0E = "#8896ae",
  base0F = "#d0d0c7",
  white = "#f1ebd1",
  darker_black = "#15161c",
  black = "#18191f", --nvim bg
  black2 = "#1e1f25",
  one_bg = "#222329",
  one_bg2 = "#28292f",
  one_bg3 = "#2e2f35",
  grey = "#38393f",
  grey_fg = "#43444a",
  grey_fg2 = "#48494f",
  light_grey = "#505157",
  red = "#a67476",
  baby_pink = "#d6b3bd",
  pink = "#c99aa7",
  line = "#24252b", --for lines like vertsplit
  green = "#8aa387",
  vibrant_green = "#94ad91",
  nord_blue = "#8d9bb3",
  blue = "#5a6986",
  yellow = "#ccb89c",
  sun = "#deb88a",
  purple = "#b8aad9",
  dark_purple = "#a99bca",
  teal = "#7aacaa",
  orange = "#c8916d",
  cyan = "#90a0a0",
  statusline_bg = "#1d1e24",
  lightbg = "#2b2c32",
  lightbg2 = "#24252b",
  pmenu_bg = "#8aa387",
  folder_bg = "#90a0a0",
}

local cp = {
  -- Legacy colors for compatibility
  red = base.red,
  yellow = base.yellow,
  orange = base.orange,
  magenta = base.dark_purple,
  blue = base.blue,
  green = base.green,
  cyan = base.teal,

  -- The new shiny boy
  directory = base.folder_bg,
  fg = base.white,
  diff = {
    add = base.green,
    remove = base.red,
    text = base.blue,
    change = base.yellow,
  },
  accent = base.base0C,
  search_result = { fg = base.base01, bg = base.base0A, telescope = base.base0A },
  match = base.base06,
  dimmed = {
    inactive = base.base03,
    subtle = base.grey_fg,
  },
  bg = {
    base = base.base00,
    alt = base.darker_black,
    selected = base.base02,
  },
  border = base.blue,
  syntax = {
    statement = base.base08,
    ["function"] = base.base0D,
    variable = base.base05,
    include = base.base0D,
    keyword = base.base0E,
    struct = base.base0E,
    string = base.base0B,
    identifier = base.base08,
    field = base.base0A,
    parameter = base.base08,
    property = base.base08,
    punctuation = base.base0F,
    constructor = base.base0C,
    operator = base.base05,
    preproc = base.base0A,
    constant = base.base09,
    todo = { fg = base.base0A, bg = base.base01 },
    number = base.base09,
    comment = base.base03,
    conditional = base.base0E,
  },
  built_in = {
    ["function"] = base.base0C,
    type = base.base0A,
    variable = base.base0C,
    keyword = base.base0E,
    constant = base.base09,
  },
  diagnostic = {
    error = base.red,
    warn = base.yellow,
    info = base.green,
    hint = base.purple,
  },
  inc_search = { fg = base.base01, bg = base.base09 },
  uri = base.base08,
  pum = {
    fg = base.base06,
    bg = base.one_bg,
    sbar = base.one_bg2,
    thumb = base.nord_blue,
    sel = {
      bg = base.pmenu_bg,
      fg = base.base05,
    },
  },
  heading = {
    h1 = base.blue,
    h2 = base.blue,
  },
}

return cp
