return {
  ["accent"] = "#ebbcba",
  ["search_result"] = {
    ["telescope"] = "#ebbcba",
    ["bg"] = "#403d52",
    ["fg"] = "#e0def4",
  },
  ["cursorlinenr"] = "#e0def4",
  ["dimmed"] = {
    ["inactive"] = "#6e6a86",
    ["subtle"] = "#6e6a86",
  },
  ["match"] = "#e0def4",
  ["inc_search"] = {
    ["fg"] = "#191724",
    ["bg"] = "#ebbcba",
  },
  ["magenta"] = "#c4a7e7",
  ["yellow"] = "#f6c177",
  ["border"] = "#403d52",
  ["diagnostic"] = {
    ["hint"] = "#c4a7e7",
    ["warn"] = "#f6c177",
    ["info"] = "#9ccfd8",
    ["error"] = "#eb6f92",
  },
  ["pum"] = {
    ["thumb"] = "#403d52",
    ["fg"] = "#908caa",
    ["sel"] = {
      ["fg"] = "#e0def4",
      ["bg"] = "#26233a",
    },
    ["bg"] = "#1f1d2e",
    ["sbar"] = "#21202e",
  },
  ["remaps"] = {
    ["core"] = {
      ["Visual"] = {
        ["bg"] = "# 403d52",
      },
    },
  },
  ["built_in"] = {
    ["function"] = "#eb6f92",
    ["variable"] = "#eb6f92",
    ["constant"] = "#eb6f92",
    ["keyword"] = "#31748f",
    ["type"] = "#9ccfd8",
  },
  ["bg"] = {
    ["selected"] = "#21202e",
    ["base"] = "#191724",
    ["alt"] = "#1f1d2e",
  },
  ["blue"] = "#9ccfd8",
  ["green"] = "#31748f",
  ["cyan"] = "#ebbcba",
  ["heading"] = {
    ["h1"] = "#c4a7e7",
    ["h2"] = "#e0def4",
  },
  ["gitsigns"] = {
    ["change"] = "#ebbcba",
    ["remove"] = "#eb6f92",
    ["add"] = "#9ccfd8",
  },
  ["uri"] = "#c4a7e7",
  ["diff"] = {
    ["change"] = "#26233a",
    ["remove"] = "#82435b",
    ["add"] = "#5b737e",
    ["text"] = "#826a6f",
  },
  ["syntax"] = {
    ["field"] = "#9ccfd8",
    ["statement"] = "#31748f",
    ["preproc"] = "#c4a7e7",
    ["punctuation"] = "#6e6a86",
    ["struct"] = "#9ccfd8",
    ["operator"] = "#908caa",
    ["conditional"] = "#31748f",
    ["comment"] = "#6e6a86",
    ["property"] = "#c4a7e7",
    ["constructor"] = "#9ccfd8",
    ["include"] = "#c4a7e7",
    ["string"] = "#f6c177",
    ["constant"] = "#9ccfd8",
    ["number"] = "#f6c177",
    ["type"] = "#9ccfd8",
    ["function"] = "#ebbcba",
    ["variable"] = "#e0def4",
    ["tag"] = "#9ccfd8",
    ["keyword"] = "#31748f",
    ["todo"] = {
      ["fg"] = "#c4a7e7",
      ["bg"] = "#e0def4",
    },
    ["parameter"] = "#c4a7e7",
  },
  ["orange"] = "#f6c177",
  ["fg"] = "#e0def4",
}
