return {
  ["cyan"] = "#ebbcba",
  ["uri"] = "#f6c177",
  ["cursorlinenr"] = "#6ea86",
  ["magenta"] = "#c4a7e7",
  ["fg"] = "#e0def4",
  ["green"] = "#9ccfd8",
  ["accent"] = "#ebbcba",
  ["search_result"] = { ["fg"] = "#12121e", ["telescope"] = "#ebbcba", ["bg"] = "#ebbcba" },
  ["diff"] = { ["remove"] = "#0", ["add"] = "#0", ["text"] = "#0", ["change"] = "#0" },
  ["heading"] = { ["h1"] = "#ebbcba", ["h2"] = "#0" },
  ["blue"] = "#3e8fb0",
  ["yellow"] = "#f6c177",
  ["syntax"] = {
    ["type"] = "#9ccfd8",
    ["todo"] = { ["fg"] = "#c4a7e7", ["bg"] = "#0" },
    ["function"] = "#ebbcba",
    ["conditional"] = "#3e8fb0",
    ["statement"] = "#3e8fb0",
    ["field"] = "#9ccfd8",
    ["variable"] = "#e0def4",
    ["struct"] = "#9ccfd8",
    ["number"] = "#f6c177",
    ["keyword"] = "#3e8fb0",
    ["tag"] = "#9ccfd8",
    ["include"] = "#c4a7e7",
    ["parameter"] = "#c4a7e7",
    ["preproc"] = "#c4a7e7",
    ["property"] = "#c4a7e7",
    ["comment"] = "#555169",
    ["string"] = "#f6c177",
    ["punctuation"] = "#6e6a86",
    ["constructor"] = "#9ccfd8",
    ["operator"] = "#3e8fb0",
    ["constant"] = "#9ccfd8",
  },
  ["border"] = "#6e6a86",
  ["diagnostic"] = { ["hint"] = "#c4a7e7", ["warn"] = "#f6c177", ["info"] = "#9ccfd8", ["error"] = "#ff789e" },
  ["built_in"] = {
    ["type"] = "#9ccfd8",
    ["variable"] = "#ff789e",
    ["function"] = "#ff789e",
    ["keyword"] = "#3e8fb0",
    ["constant"] = "#ff789e",
  },
  ["inc_search"] = { ["bg"] = "#ff789e", ["fg"] = "#12121e" },
  ["pum"] = {
    ["sbar"] = "#26233a",
    ["fg"] = "#6e6a86",
    ["thumb"] = "#555169",
    ["bg"] = "#1e1e2e",
    ["sel"] = { ["bg"] = "#26233a", ["fg"] = "#e0def4" },
  },
  ["dimmed"] = { ["subtle"] = "#6e6a86", ["inactive"] = "#555169" },
  ["match"] = "#ebbcba",
  ["bg"] = { ["base"] = "#12121e", ["alt"] = "#1e1e2e", ["selected"] = "#211f2d" },
  ["orange"] = "#f6c177",
}
