local colors = {
  bg = "#1a1b26",
  bg_dark = "#16161e",
  bg_float = "#24283b",
  bg_highlight = "#292e42",
  bg_popup = "#1f2335",
  bg_search = "#3d59a1",
  bg_sidebar = "#24283b",
  bg_statusline = "#1f2335",
  bg_visual = "#364A82",
  black = "#1D202F",
  blue = "#7aa2f7",
  blue0 = "#3d59a1",
  blue1 = "#2ac3de",
  blue2 = "#0db9d7",
  blue5 = "#89ddff",
  blue6 = "#B4F9F8",
  blue7 = "#394b70",
  border = "#1D202F",
  border_highlight = "#3d59a1",
  comment = "#565f89",
  cyan = "#7dcfff",
  dark3 = "#545c7e",
  dark5 = "#737aa2",
  diff = {
    add = "#283B4D",
    change = "#272D43",
    remove = "#3F2D3D",
    text = "#394b70",
  },
  error = "#db4b4b",
  fg = "#c0caf5",
  fg_dark = "#a9b1d6",
  fg_gutter = "#3b4261",
  fg_sidebar = "#a9b1d6",
  git = {
    add = "#449dab",
    change = "#6183bb",
    conflict = "#bb7a61",
    delete = "#914c54",
    ignore = "#545c7e",
  },
  gitSigns = {
    add = "#266d6a",
    change = "#536c9e",
    delete = "#b2555b",
  },
  green = "#9ece6a",
  green1 = "#73daca",
  green2 = "#41a6b5",
  hint = "#1abc9c",
  info = "#0db9d7",
  magenta = "#bb9af7",
  magenta2 = "#ff007c",
  none = "NONE",
  orange = "#ff9e64",
  purple = "#9d7cd8",
  red = "#f7768e",
  red1 = "#db4b4b",
  teal = "#1abc9c",
  terminal_black = "#414868",
  warning = "#e0af68",
  yellow = "#e0af68",
}

local cp = {
  -- Legacy colors for compatibility
  red = colors.red,
  yellow = colors.yellow,
  orange = colors.orange,
  magenta = colors.magenta,
  blue = colors.blue,
  green = colors.green,
  cyan = colors.cyan,

  -- The new shiny boy
  fg = colors.fg,
  diff = colors.diff,
  accent = colors.blue1,
  directory = colors.blue,
  search_result = { bg = colors.bg_search, fg = colors.fg, telescope = colors.fg },
  match = colors.blue1,
  dimmed = {
    linenr = colors.fg_gutter,
    inactive = colors.dark3,
    subtle = colors.fg_dark,
  },
  bg = {
    base = colors.bg,
    alt = colors.bg_float,
    selected = colors.bg_highlight,
  },
  border = colors.border,
  syntax = {
    statement = colors.magenta,
    ["function"] = colors.blue,
    variable = colors.fg,
    include = colors.cyan,
    keyword = colors.magenta,
    struct = colors.orange,
    string = colors.green,
    field = colors.green1,
    parameter = colors.yellow,
    property = colors.green1,
    punctuation = colors.fg_dark,
    constructor = colors.magenta,
    operator = colors.blue5,
    preproc = colors.cyan,
    constant = colors.orange,
    todo = { fg = colors.bg, bg = colors.yellow },
    number = colors.orange,
    comment = colors.comment,
    type = colors.blue1,
    conditional = colors.magenta,
  },
  built_in = {
    ["function"] = colors.blue1,
    type = colors.blue1,
    variable = colors.red,
    keyword = colors.magenta,
    constant = colors.blue1,
  },
  diagnostic = {
    error = colors.error,
    warn = colors.warning,
    info = colors.info,
    hint = colors.hint,
  },
  inc_search = { bg = colors.orange, fg = colors.black },
  uri = colors.fg,
  pum = {
    fg = colors.fg,
    bg = colors.bg_popup,
    sbar = "#222229",
    thumb = colors.fg_gutter,
    sel = {
      bg = "#343A55",
      fg = colors.fg,
    },
  },
  heading = {
    h1 = colors.magenta,
    h2 = colors.blue,
  },
}

return cp
