local colors = {
    black0 = "#161616",
    black1 = "#262626",
    black2 = "#393939",
    black3 = "#525252",
    white0 = "#FDFDFD",
    white1 = "#FAFAFA",
    white2 = "#FFFFFF",
    grey0 = "#c1c7cd",
    grey1 = "#dde1e6",
    grey2 = "#f2f4f8",
    green = "#42be65",
    cyan = "#3ddbd9",
    blue = "#33b1ff",
    red = "#ff8080",
    yellow = "#ffff80",
    purple = "#be95ff",
}

local cp = {
    fg = colors.grey2,
    bg = {
        base = colors.black0,
        alt = colors.black1,
        selected = colors.black2,
    },
    dimmed = {
        inactive = colors.black3,
        subtle = colors.black3,
    },
    diff = {
        add = colors.green,
        delete = colors.red,
        change = colors.yellow,
        text = colors.white1,
    },
    accent = colors.purple,
    inc_search = {
        fg = colors.white0,
        bg = colors.blue,
    },
    search_result = {
        fg = colors.white0,
        bg = colors.cyan,
        telescope = colors.white0,
    },
    match = colors.cyan,
    border = colors.black1,
    uri = colors.purple,
    heading = {
        h1 = colors.blue,
        h2 = colors.cyan,
    },
    syntax = {
        statement = colors.green,
        ["function"] = colors.blue,
        variable = colors.grey1,
        include = colors.cyan,
        keyword = colors.purple,
        struct = colors.cyan,
        string = colors.green,
        field = colors.purple,
        parameter = colors.cyan,
        property = colors.blue,
        punctuation = colors.grey0,
        constructor = colors.purple,
        operator = colors.yellow,
        preproc = colors.yellow,
        constant = colors.blue,
        todo = {
            fg = colors.white0,
            bg = colors.red,
        },
        number = colors.cyan,
        comment = colors.black3,
        ["type"] = colors.green,
        conditional = colors.blue,
    },
    built_in = {
        ["function"] = colors.blue,
        ["type"] = colors.green,
        variable = colors.red,
        keyword = colors.blue,
        constant = colors.blue,
    },
    diagnostic = {
        ["error"] = colors.red,
        want = colors.yellow,
        info = colors.green,
        hint = colors.cyan,
    },
    pum = {
        fg = colors.grey2,
        bg = colors.black2,
        sbar = colors.grey1,
        thumb = colors.grey2,
        sel = {
            bg = colors.black3,
            fg = colors.grey2,
        },
    },
}

return cp
